### ISSUE TITLE
Write a Code of Conduct

### ISSUE THREAD

**Issue by ericlathrop** [louisvilleio/louisville.io#15]
We need a code-of-conduct that everyone sees when they first log into the chat room. This will set expectations about acceptable behaviour, avenues of reporting a problem, and repercussions. We want the Louisville.io chat to be a safe, friendly, environment where people feel welcome.

**Comment by ericlathrop** [comment]
I'm happy to steal a CoC from somewhere else if it's good.

**Comment by ericlathrop** [comment]
Examples:
https://www.djangoproject.com/conduct/
http://www.rust-lang.org/conduct.html
https://github.com/nodejs/io.js/blob/master/CONTRIBUTING.md#code-of-conduct

**Comment by ericlathrop** [comment]
http://contributor-covenant.org/

**Comment by barake** [comment]
The irc.perl.org network has a decent set of rules that is short and pretty clear. Check out the "Community Policies" section at http://www.irc.perl.org/rules.html

**Comment by ericlathrop** [comment]
I've read through all the linked ones and found this:
http://citizencodeofconduct.org/
It's my favorite of all of them.

**Comment by myared** [comment]
Agreed. I made some custom edits. Once we have something online, we can send it to slack upon first sign-on.

https://github.com/myared/policies/pull/2

**Comment by EmSchw** [comment]
I like that one as well, Eric.  Looks like just a couple edits are needed.

**Comment by ericlathrop** [comment]
From @barake : https://github.com/todogroup/opencodeofconduct/blob/gh-pages/index.md

**Comment by bretwalker** [comment]
:+1: for doing this!

**Comment by UkiahSmith** [comment]
Done, closing: http://louisville.io/code-of-conduct.html
