### ISSUE TITLE
Readme steps to generate site cause error

### ISSUE THREAD

**Issue by jcottrell** [louisvilleio/louisville.io#47]
I installed the newest node and npm, as requested. `npm install` went smoothly. `npm run build` caused an error on the `unfold site.json`

    Error: File to import not found or unreadable: ./node_modules/node-bourbon/node_modules/bourbon/app/assets/stylesheets/bourbon

This is caused because `npm install` will install node-bourbon and node-neat but does not do an `npm install` in those packages, causing the paths in src/css/main.scss to fail because the inner level of "node_modules" does not exist.

One solution is to add bourbon and bourbon-neat to the dependencies and then change the paths in main.scss. I should have a pull request ready soon.

**Comment by ericlathrop** [comment]
@jcottrell Did you install Node 5.x? The 4.x "LTS" versions don't work because we need NPM 3, which is bundled in Node 5.

**Comment by jcottrell** [comment]
Yes, `node -v` gives me v5.10.1 and `npm -v` gives 3.8.6

**Comment by ericlathrop** [comment]
Ah sorry, I was a little fuzzy about where I left this issue. I actually have a branch at https://github.com/louisvilleio/louisville.io/tree/fix-paths-npm-3 that fixes this issue, but I haven't merged it to master because it would break everyone on NPM 2, so I was waiting a while.

**Comment by jcottrell** [comment]
Ah, ok. Very good.

**Comment by ericlathrop** [comment]
Sorry for the confusion.
