### ISSUE TITLE
Slack returning token_revoked when trying to get an invitation

### ISSUE THREAD

**Issue by scottcorgan** [louisvilleio/louisville.io#62]
I have student in Code Lousiville trying to get an invitation from the slack button on the homepage. She keeps getting the response `token_revoked`. I'm not sure if it's a Slack issue or a if it's a Louisville.io issue.

Is there anything you can do?

/cc @ericlathrop

**Comment by JVette** [comment]
I got in this morning!!  No issues!  Thank you.

**Comment by ericlathrop** [comment]
@scottcorgan Yeah, I had mistakenly deleted my API token last week. I fixed it this morning.
