### ISSUE TITLE
Add co-working spaces

### ISSUE THREAD

**Issue by ericlathrop** [louisvilleio/louisville.io#8]
We should include a listing of co-working spaces.

**Comment by aarontropy** [comment]
Would you consider a coffee shop with quality wifi a co-working space?

**Comment by Supermighty** [comment]
I would say no. 
On Jun 19, 2015 9:27 AM, Aaron Johnson <notifications@github.com> wrote:Would you consider a coffee shop with quality wifi a co-working space?

**Comment by ericlathrop** [comment]
We should start with this list. https://gist.github.com/ericlathrop/25378ebe2f3e640e5b14#coworking-spaces-in-louisville-kentucky

**Comment by pbking** [comment]
in or... near louisville? Etown to far away? Would love to have COE on any list we can.
