### ISSUE TITLE
Add "changes" page

### ISSUE THREAD

**Issue by ericlathrop** [louisvilleio/louisville.io#9]
Should describe how to report inaccuracies or get new groups added to the site.

**Comment by ericlathrop** [comment]
We need someone to write up the process.

**Comment by slogsdon** [comment]
I can do this, might need some tips on what the process is though :smile:

**Comment by ericlathrop** [comment]
Currently the process is send a pull request including
1. add group data to [groups.json](https://github.com/louisvilleio/louisville.io/blob/master/data/groups.json)
2. add group icon to [src/group-icons](https://github.com/louisvilleio/louisville.io/tree/master/src/group-icons)

**Comment by ericlathrop** [comment]
The most important thing in the group data is to have a calendar URL that points to an ICS format calendar. This is where the site pulls events from.

**Comment by slogsdon** [comment]
sounds straightforward :+1:
